### ISSUE TITLE
Use via ExtUtils::Depends

### ISSUE THREAD

**Issue by Grinnz** [Perl5-Alien/Alien-Build#107]
I am trying to convert Protocol::Redis::XS to use Alien::hiredis. It uses ExtUtils::Depends, so I replaced the custom arguments that were building hiredis with the Alien as suggested in the Alien::Base docs.

https://github.com/dgl/protocol-redis-xs/compare/use_alien_hiredis

But I get this error upon trying to 'make':

```
cp lib/Protocol/Redis/XS.pm blib/lib/Protocol/Redis/XS.pm
Running Mkbootstrap for XS ()
chmod 644 "XS.bs"
"/home/grinnz/.plenv/versions/5.28.1x/bin/perl5.28.1" -MExtUtils::Command::MM -e 'cp_nonempty' -- XS.bs blib/arch/auto/Protocol/Redis/XS/XS.bs 644
"/home/grinnz/.plenv/versions/5.28.1x/bin/perl5.28.1" "/home/grinnz/.plenv/versions/5.28.1x/lib/perl5/5.28.1/ExtUtils/xsubpp"  -typemap '/home/grinnz/.plenv/versions/5.28.1x/lib/perl5/5.28.1/ExtUtils/typemap' -typemap '/home/grinnz/.plenv/versions/5.28.1x/lib/perl5/site_perl/5.28.1/x86_64-linux/XS/Object/Magic/Install/typemap' -typemap '/home/grinnz/projects/protocol-redis-xs/typemap'  XS.xs > XS.xsc
mv XS.xsc XS.c
cc -c  -I/home/grinnz/.plenv/versions/5.28.1x/lib/perl5/site_perl/5.28.1/x86_64-linux/Alien/hiredis/Install -I/home/grinnz/.plenv/versions/5.28.1x/lib/perl5/site_perl/5.28.1/x86_64-linux/XS/Object/Magic/Install -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O2   -DVERSION=\"0.05\" -DXS_VERSION=\"0.05\" -fPIC "-I/home/grinnz/.plenv/versions/5.28.1x/lib/perl5/5.28.1/x86_64-linux/CORE"   XS.c
XS.xs:3:10: fatal error: hiredis.h: No such file or directory
 #include "hiredis.h"
          ^~~~~~~~~~~
compilation terminated.
make: *** [Makefile:339: XS.o] Error 1
```

These are the args it seems to be adding:

```
          'LIBS' => '-L/home/grinnz/.plenv/versions/5.28.1x/lib/perl5/site_perl/5.28.1/x86_64-linux/auto/share/dist/Alien-hiredis/lib -lhiredis',
           'INC' => '-I/home/grinnz/.plenv/versions/5.28.1x/lib/perl5/site_perl/5.28.1/x86_64-linux/Alien/hiredis/Install -I/home/grinnz/.plenv/versions/5.28.1x/lib/perl5/site_perl/5.28.1/x86_64-linux/XS/Object/Magic/Install',
          'TYPEMAPS' => [
                          '/home/grinnz/.plenv/versions/5.28.1x/lib/perl5/site_perl/5.28.1/x86_64-linux/XS/Object/Magic/Install/typemap'
                        ],
```
cc: @mohawk2

**Comment by plicease** [comment]
note to self: Also mentioned in the discussion on IRC: this feature is not documented in Manual::AlienUser and probably should be.

**Comment by Grinnz** [comment]
`#include "hiredis.h"` probably needs to be changed to `#include <hiredis.h>` to search include dirs since hiredis.h is no longer local, but this doesn't change the error.

**Comment by plicease** [comment]
Okay.  So it looks like ExtUtils::Depends is piggybacking on the Inline::C interface by calling `Alien::hiredis::Install::Files->Inline('C')`, which returns CCFLAGSEX and LIBS:

https://github.com/Perl5-Alien/Alien-Build/blob/831baed2437ae1b5550468a44f7b5fbc93d0299e/lib/Alien/Base.pm#L836-L839

both of these are documented in the `Inline::C` documentation.  `ExtUtils::Depends` only uses a subset of those keys, specifically `INC`, `LIBS` and `TYPEMAPS`

https://metacpan.org/release/ExtUtils-Depends/source/lib/ExtUtils/Depends.pm#L207-211

It is also adding `$instpath` which is harmless, but not necessary for Alien.  AB should probably parse out the `-I` flags from  cflags and return this as `INC` (this is more correct and also still works with `Inline::C`).  `->cflags` is commonly just `-I` flags, but there might be other things though like `-D...`, so it would be good if ExtUtils::Depends supported at least `CCFLAGSEX` and perhaps some of the other keys in the `Inline::C` interface.

**Comment by mohawk2** [comment]
Why is `Alien::hiredis::Install::Files->Inline('C')` giving `CCFLAGSEX`? Why not just `INC`? (which can be any compiler flag, btw)

**Comment by Grinnz** [comment]
I'll also note that `CCFLAGSEX` is not a documented or supported argument for EUMM...

**Comment by plicease** [comment]
`INC` is for include flags only.  The reason is that you want the dist specific `-I` flags to appear as early in the CC command as possible so that they override any `-I/usr/local/include` that might be in Perl's Config.  Other cflags should appear as late as possible in the command so that, again they override any compiler flags that might be in Perl's Config.  It may be a little pedantic, but I have had stuff fail in odd but totally legal configurations because the flags were put in the wrong bucket.

I agree that `CCFLAGSEX` isn't used or documented anywhere in EUMM, but EU::D isn't using a EUMM interface it's using the Inline::C interface, and it is documented there.  It seems to me to be roughly equivalent to MB's `extra_compiler_flags` field.  CCFLAGS isn't useful in this case because it overrides Perl's Config `ccflags`, which is bad.

**Comment by plicease** [comment]
I think I can be flexible on this.  I think support for CCFLAGSEX would be better, but to make things just work we can maybe use `INC` instead, no need to upgrad EUD.  For those that need the proper separation, they can use `Alien::Base::Wrapper`, which does split the cflags into their appropriate buckets.

**Comment by mohawk2** [comment]
That sounds like a sensible idea. If you were to have examples of things where `INC` needed to be split down so things didn't break, they could usefully be put in a ticket on EUD.

**Comment by plicease** [comment]
#109 and version 1.65 should put everything right.
