### ISSUE TITLE
Invalid curl command from Fetch::CurlCommand

### ISSUE THREAD

**Issue by Grinnz** [Perl5-Alien/Alien-Build#112]
When trying to install Alien::FFI without having Net::SSLeay installed, it falls back to Fetch::CurlCommand, which appears to generate an invalid curl command on CentOS 7 (curl 7.29.0) and Fedora 29 (curl 7.61.1).

http://www.cpantesters.org/cpan/report/81846950-62cf-11e9-a6c7-736848f64290
http://www.cpantesters.org/cpan/report/d2b9b19e-62d5-11e9-ad27-4c51d0f681c9

**Comment by plicease** [comment]
I believe 1.66_01 should address this.
