### ISSUE TITLE
Catch seg faults in with_subtest

### ISSUE THREAD

**Issue by kiwiroy** [Perl5-Alien/Alien-Build#138]
It took me longer than I'd like to admit to figure that a test was failing due to a seg fault when faced with:

```
t/02-compile.t .. All 2 subtests passed 

Test Summary Report
-------------------
t/02-compile.t (Wstat: 11 Tests: 2 Failed: 0)
  Non-zero wait status: 11
  Parse errors: No plan found in TAP output
```
The code was running the idiom `xs_ok $xs, with_subtest { ... }`

I added a `local $SIG{SEGV}`, but it occurs to me that others might benefit, if instead it is in `Test::Alien`
```patch
diff --git a/lib/Test/Alien.pm b/lib/Test/Alien.pm
index a9f8bd7..fcc5262 100644
--- a/lib/Test/Alien.pm
+++ b/lib/Test/Alien.pm
@@ -684,7 +684,13 @@ sub xs_ok
   $ok;
 }
 
-sub with_subtest (&) { $_[0]; }
+sub with_subtest (&) {
+  my $ctx = context();
+  local $SIG{SEGV} = sub {
+    $ctx->bail("Segmentation fault: $!");
+  };
+  $_[0];
+}
 
 =head2 ffi_ok
 
```

Which makes for an improved output (IMHO).

```
t/02-compile.t .. 2/? Bailout called.  Further testing stopped:  Segmentation fault: <reason>

# Failed test 'xs subtest'
# at t/02-compile.t line 40.
FAILED--Further testing stopped: Segmentation fault: <reason>
```
Test directories get cleaned if the signal handler is used.

Thoughts?

**Comment by plicease** [comment]
Agree that prove does a very bad job of indicating a SEGV.  It is usually a bit more obvious when you run the .t file directly `perl -Mblib t/02-compile.t`, but of course that can be tedious when you have lots of tests!

I'm naturally hesitant to do anything very complicated inside the signal handler, but I think worst case if it barfs again you get the confusing diagnostic again.  It would probably be worth doing some testing on older Perls which from memory do not implement signal handlers safely. Overall though I think it's a good idea.
