### ISSUE TITLE
Alien::Build::Manual::FAQ: patch example doesn't work

### ISSUE THREAD

**Issue by djerius** [Perl5-Alien/Alien-Build#14]
The patch example implies that `patch` is a built in, but apparently it is not:

```
use alienfile;

share {

    plugin Download => (
        url     => 'https://github.com/ericmandel/xpa/archive/v2.1.18.tar.gz'
    );

    patch [ '%{patch} -p1 < %{.install.patch}/v2.1.18.diffs' ];

    plugin Extract           => 'tar.gz';
    plugin 'Build::Autoconf' => ();

};
```
results in:

```
% af install --dry-run
Alien::Build> error in probe (will do a share install): No hooks registered for probe at /proj/axaf/ots/pkgs/perl-5.22/x86_64-linux_debian-7/lib/site_perl/5.22.1/Alien/Build.pm line 282.
Can't locate Alien/patch.pm in @INC (you may need to install the Alien::patch module)
```

Also, is there a glossary somewhere which defines what the interpolated variables are? Where is `%{.install.patch}`?

**Comment by plicease** [comment]
Add a probe directive to your `alienfile`:

```
probe { 'share' }
```

This works if your alien doesn't do a system probe, which I do not encourage.  I will update the documentation when I get a chance.

Standard properties that are available are listed here:

https://metacpan.org/pod/Alien::Build#PROPERTIES

plugins and alienfiles can also define their own properties, and should be documented as a appropriate.

Please leave this bug open I'd like to update the documentation!

**Comment by djerius** [comment]
I think it might be helpful to describe what the different phases are.  For instance, what does the gather phase do?  I discovered (through lots of debugging after mistyping the package name in the PkgConfig plugin argument) that it assembles the runtime properties.  What else does it do?

**Comment by plicease** [comment]
It should only be gathering runtime properties.
