### ISSUE TITLE
Forcing an install to ignore a system library

### ISSUE THREAD

**Issue by djerius** [Perl5-Alien/Alien-Build#15]
Is there generic mechanism to ignore an installed library? For example, if an existing system library is out-of-date, I'd like to be able to use an environment variable to inform Alien::Build to ignore it and download and build from scratch.

Thanks,
Diab

**Comment by plicease** [comment]
Are we talking ignoring a specific version?  Yes there is a way to do this but needs to be documented better.  Also a good helper plugin for doing this is on my todo list.

**Comment by djerius** [comment]
Not necessarily for a specific version.  Here are a couple examples:

1. I'm testing my own Alien packaging for libraries which are already installed (e.g. "system" libraries).  In order to test whether the download+build code path works, I need to turn off the `pkg-config` probing, but I can't (?) do that within the alienfile without  also breaking gathering of the `runtime_props`, as the `PkgConfig` plugin performs both probe and gather functionality.  At the moment I am renaming the `pkg-config` `.pc` files so they are not found (and hoping that I'm not breaking other's compilation runs). 

1. There's a server at work where the system installation of `libgd` combined with a more up-to-date installation in `/usr/local` makes building things essentially impossible (circular conflicting dependencies for `libgd` dependencies, etc. Don't Ask).  I can't fix it, so would prefer to simply ignore all existing installations.

**Comment by plicease** [comment]
When I wrote that comment I was for some reason thinking about skipping specific versions from a share install.  Please nevermind that.

For testing, or for preference you can use the `ALIEN_INSTALL_TYPE` environment variable.  Setting it to `share` will skip the system probe.  You can also set it to `system` to not allow a share install.  I use this in travis to make sure that both paths are tested for example:

https://github.com/Perl5-Alien/Alien-patch/blob/master/.travis.yml#L23

**Comment by djerius** [comment]
Thanks. `ALIEN_INSTALL_TYPE` is exactly what I need.
