### ISSUE TITLE
RFE: strictures in ${mod}::Install::Files.pm

### ISSUE THREAD

**Issue by djerius** [Perl5-Alien/Alien-Build#162]
Howdy,

I tend to run lots of checks against my code, one of which is `perlcritic`.  Unfortunately, the `::Install::Files.pm` file generated by `Alien::Build` doesn't turn on warnings and structures, which causes the` [TestingAndDebugging::RequireUseStrict]` test to fail.

Normally I'd work around this, but since `::Install::Files.pm` is generated outside of my control, and I can't figure out how to restrict `perlcritic` tests to a subset of the files, I'm stuck.

Would you be amenable to one of the following solutions?

1. Add `use warnings; use strict;` to the emitted code
1. Add a Perlcritic comment which would disable the strictures test.  There's precedent for this already, as `Pod::Coverage` is being handled similarly.  This would have no runtime costs.

Thanks,
Diab

**Comment by Grinnz** [comment]
Adding strict and warnings to this generated module seems reasonable

**Comment by plicease** [comment]
I'm not sure why strict and warnings isn't turned on for these files.  I think it should be okay, and probably even desirable to turn them on.

https://github.com/Perl5-Alien/Alien-Base-ModuleBuild/pull/17
https://github.com/Perl5-Alien/Alien-Build/pull/163
https://github.com/Perl5-Alien/Alien-Build-MB/issues/4

**Comment by djerius** [comment]
See PR #165

**Comment by plicease** [comment]
Implemented in 2.03_01.
