### ISSUE TITLE
Test::Alien::xs_ok requires explicit LD_RUN_PATH to find its just compiled alien library 

### ISSUE THREAD

**Issue by djerius** [Perl5-Alien/Alien-Build#172]
# System
Test::Alien 2.04
Debian 10

# Summary
My [alien module](https://gitlab.com/djerius/alien-libciaoregion) compiles its own copy of the alien library if it is not found on the system.  `Test::Alien::xs_ok()` doesn't find the compiled library unless I explicitly set an `LD_RUN_PATH` in the environment.

# Alienfile

The [alienfile](https://gitlab.com/djerius/alien-libciaoregion/-/blob/master/alienfile) is fairly generic:
```
use strict;
use warnings;
use alienfile;
use File::Which 'which' ;

plugin 'PkgConfig' => (
  pkg_name => 'cxcregion',
);

probe [ 'pkg-config --exists libcxcregion' ];

share {
    which( 'bison' ) // which( 'yacc' ) // die( "yacc/bison executable not found" );
    which( 'flex' ) // which( 'lex' ) //  die( "flex/lex executable not found" );
    start_url 'inc/cxcregion-4.12.0.1.tar.gz';
    plugin 'Download';
    plugin 'Extract' => 'tar.gz';
    plugin 'Build::Autoconf' => ( with_pic => 1 );

    build [
           '%{configure}',
           '%{make}',
           '%{make} install',
          ];
};

gather [
  [ 'pkg-config --modversion libcxcregion', \'%{.runtime.version}' ],
  [ 'pkg-config --cflags     libcxcregion', \'%{.runtime.cflags}'  ],
  [ 'pkg-config --libs       libcxcregion', \'%{.runtime.libs}'    ],
];
```
# Test runs

## No `LD_RUN_PATH`
Here's what[ it looks like](https://gitlab.com/djerius/alien-libciaoregion/-/jobs/438399985#L966url) without the `LD_RUN_PATH`:
```
 $ make test
"/usr/bin/perl" -MAlien::Build::MM=cmd -e test
Alien::Build::Plugin::PkgConfig::Negotiate> Using PkgConfig plugin: PkgConfig::CommandLine
PERL_DL_NONLAZY=1 "/usr/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/ffi.t .. ok
# Failed test 'xs'
# at t/xs.t line 12.
#   XSLoader failed
#     Can't load '/builds/djerius/alien-libciaoregion/_alien/tmp/test-alien-zixFyd/auto/Test/Alien/XS/Mod0/Mod0.so' for module Test::Alien::XS::Mod0: libcxcregion.so.0: cannot open shared object file: No such file or directory at /usr/lib/x86_64-linux-gnu/perl/5.28/DynaLoader.pm line 187.
# 
```
## `LD_RUN_PATH` set

Here's [what it looks like](https://gitlab.com/djerius/alien-libciaoregion/-/jobs/438402175#L962) with `LD_RUN_PATH=blib/lib/auto/share/dist/Alien-LibCIAORegion/lib`
```
$ make test
"/usr/bin/perl" -MAlien::Build::MM=cmd -e test
Alien::Build::Plugin::PkgConfig::Negotiate> Using PkgConfig plugin: PkgConfig::CommandLine
PERL_DL_NONLAZY=1 "/usr/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/ffi.t .. ok
t/xs.t ... ok
All tests successful.
```
# How to duplicate
I set up a docker container which has everything installed to duplicate this:

Steps to duplicate this:
```
IMAGE_ID=$(podman pull -q registry.gitlab.com/djerius/alien-libciaoregion)
podman run -it --rm $IMAGE_ID
cd /tmp/Alien-LibCIAORegion-0.01
perl Makefile.PL
make
make test
LD_RUN_PATH=blib/lib/auto/share/dist/Alien-LibCIAORegion/lib make test
```

**Comment by Grinnz** [comment]
Perhaps you need https://metacpan.org/pod/Alien::Build::Plugin::Gather::IsolateDynamic so the XS does not build against the shared library, as the manuals have recently been updated to discuss.

**Comment by plicease** [comment]
Indeed the TL;DR is use `Gather::IsolateDynamic`.  The manual has been updated here may be of some help:

https://metacpan.org/pod/distribution/Alien-Build/lib/Alien/Build/Manual/AlienAuthor.pod#A-note-about-dynamic-vs.-static-libraries

Also I recommend that if you need flex/bison that you use `Alien::flex` and `Alien::bison`:

```perl
share {
  ...
  requires 'Alien::flex';
  requires 'Alien::bison';
  ...
};
```

**Comment by djerius** [comment]
Thanks!  that does the trick.

My apologies for not perusing the documentation more closely.

**Comment by plicease** [comment]
👍 no problem, the documentation is quite new and depending on when you got started you might have missed it.
