### ISSUE TITLE
t/test_alien.t fails on at least some cpantesters with mswin32 + Visual C++ Perl

### ISSUE THREAD

**Issue by plicease** [Perl5-Alien/Alien-Build#185]
I can't reproduce this currently.  I have extensively tested with my own build of Visual C++ Perl in the 5.31.x series.

http://www.cpantesters.org/cpan/report/185494e4-6942-11ea-9066-e374b0ba08e8
https://gist.github.com/plicease/dc8033e57c03836bcf367f5df2afc484

Came from @bingos.

I will see if I can add some useful diagnostics in the next release, but @bingos if you could provide full output of `perl -Mblib t/test_alien.t` that will be helpful.

I *can* tell from the failure counts that it is failing the xs tests.

**Comment by plicease** [comment]
@bingos Do you think you could please provide me with the verbose output of this test?

**Comment by plicease** [comment]
I am not able to reproduce a test 5 or 7 fail in `test_alient.t` that doesn't produce at least some `diag` output, so this is hard to debug without the verbose output.

**Comment by bingos** [comment]
Circumstances meant I only got around to testing this today. I tested with 2.18_01 and it has successfully built, tested and installed:

![image](https://user-images.githubusercontent.com/62011/78655758-5a295900-78be-11ea-86f2-802324eade8b.png)

**Comment by plicease** [comment]
Let's re-open if we see this again.

**Comment by plicease** [comment]
Thanks for running a tester with VC Perl!
