### ISSUE TITLE
t/test_alien.t runs forever on latest Cygwin64

### ISSUE THREAD

**Issue by EdwardMauthe** [Perl5-Alien/Alien-Build#187]
With Perl v5.26.3 installed on the latest Cygwin64 DLL
Trying to install Alien::Build
`cpan install Alien::Build`

The test t/test_alien.t runs forever with error:
`child_info_fork::abort: unable to map ... Win32 error 126`

I can understand if the Module isn't supported with Cygwin but is there any way to bypass or remove this test to at least bypass it?

### Console Output
t/alien_build_plugin_probe_vcpkg.t ................... skipped: Test requires Win32::Vcpkg 0.02
t/alien_build_plugin_test_mock.t ..................... ok
t/alien_build_rc.t ................................... ok
t/alien_build_temp.t ................................. ok
t/alien_build_tempdir.t .............................. ok
t/alien_build_util.t ................................. ok
t/alien_build_version_basic.t ........................ ok
t/alien_role.t ....................................... ok
t/alienfile.t ........................................ ok
t/test_alien.t ....................................... 1/?
2 [main] perl 11673 child_info_fork::abort: unable to map \??\C:\cygwin64\home\CygwinUser\.cpan\build\Alien-Build-2.19-0\.tmp\test-alien-xXUXni\auto\Test\Alien\XS\Mod0\Mod0.dll (using C:\cygwin64\home\CygwinUser\.cpan\build\Alien-Build-2.19-0\.tmp\test-alien-xXUXni\auto\Test\Alien\XS\Mod0\Mod0.dll), Win32 error 126
      1 [main] perl 11674 child_info_fork::abort: unable to map \??\C:\cygwin64\home\CygwinUser\.cpan\build\Alien-Build-2.19-0\.tmp\test-alien-xXUXni\auto\Test\Alien\XS\Mod0\Mod0.dll (using C:\cygwin64\home\CygwinUser\.cpan\build\Alien-Build-2.19-0\.tmp\test-alien-xXUXni\auto\Test\Alien\XS\Mod0\Mod0.dll), Win32 error 126

**Comment by EdwardMauthe** [comment]
Upgraded to Cygwin Perl v5.30.2 and Alien::Build was already installed.

**Comment by plicease** [comment]
Duplicated of #153

**Comment by plicease** [comment]
Fixed in 2.20
