### ISSUE TITLE
Alien::Build::MM::clean_install | incomplete share installs under parallel make

### ISSUE THREAD

**Issue by shawnlaffan** [Perl5-Alien/Alien-Build#197]
This is possibly a red herring, but it appears that the clean_install option can result in incomplete installs under parallel make.   

The URL below is for a Cirrus CI build of Alien::gdal for which Alien::proj was built using ```MAKEFLAGS=-j4 cpanm -v Alien::proj~1.07```, for which the version at the time was 1.12 and which used the clean_install option in Makefile.PL.   
https://cirrus-ci.com/task/5404952254218240?command=main#L6

The thing to note is that the file listing under the Alien::proj dist_dir is missing the ```include``` dir.  This results in a failed Alien::gdal build.  

The issue disappears when I disable the clean_install option.

What might be happening is that the parallel make calls are trying to copy files across at the same time that the target dir is being cleaned up.

I don't know enough about makefiles to work up a patch, but if it is a parallel problem then the cleanup might need to be a deeper level install prereq, or the parallel make could be disabled for the install target.  The former would be complex to implement, the latter should not make too much difference for the install step (one hopes).

And just for reference, the install section of the makefile looks like this when clean_install is specified:
```make
# --- MakeMaker install section:
install :: alien_clean_install


install :: pure_install doc_install
	$(NOECHO) $(NOOP)

install_perl :: pure_perl_install doc_perl_install
	$(NOECHO) $(NOOP)

install_site :: pure_site_install doc_site_install
	$(NOECHO) $(NOOP)

install_vendor :: pure_vendor_install doc_vendor_install
	$(NOECHO) $(NOOP)

pure_install :: pure_$(INSTALLDIRS)_install
	$(NOECHO) $(NOOP)

doc_install :: doc_$(INSTALLDIRS)_install
	$(NOECHO) $(NOOP)

pure__install : pure_site_install
	$(NOECHO) $(ECHO) INSTALLDIRS not defined, defaulting to INSTALLDIRS=site

doc__install : doc_site_install
	$(NOECHO) $(ECHO) INSTALLDIRS not defined, defaulting to INSTALLDIRS=site

pure_perl_install :: all
	$(NOECHO) $(MOD_INSTALL) \
		read "$(PERL_ARCHLIB)\auto\$(FULLEXT)\.packlist" \
		write "$(DESTINSTALLARCHLIB)\auto\$(FULLEXT)\.packlist" \
		"$(INST_LIB)" "$(DESTINSTALLPRIVLIB)" \
		"$(INST_ARCHLIB)" "$(DESTINSTALLARCHLIB)" \
		"$(INST_BIN)" "$(DESTINSTALLBIN)" \
		"$(INST_SCRIPT)" "$(DESTINSTALLSCRIPT)" \
		"$(INST_MAN1DIR)" "$(DESTINSTALLMAN1DIR)" \
		"$(INST_MAN3DIR)" "$(DESTINSTALLMAN3DIR)"
	$(NOECHO) $(WARN_IF_OLD_PACKLIST) \
		"$(SITEARCHEXP)\auto\$(FULLEXT)"


pure_site_install :: all
	$(NOECHO) $(MOD_INSTALL) \
		read "$(SITEARCHEXP)\auto\$(FULLEXT)\.packlist" \
		write "$(DESTINSTALLSITEARCH)\auto\$(FULLEXT)\.packlist" \
		"$(INST_LIB)" "$(DESTINSTALLSITELIB)" \
		"$(INST_ARCHLIB)" "$(DESTINSTALLSITEARCH)" \
		"$(INST_BIN)" "$(DESTINSTALLSITEBIN)" \
		"$(INST_SCRIPT)" "$(DESTINSTALLSITESCRIPT)" \
		"$(INST_MAN1DIR)" "$(DESTINSTALLSITEMAN1DIR)" \
		"$(INST_MAN3DIR)" "$(DESTINSTALLSITEMAN3DIR)"
	$(NOECHO) $(WARN_IF_OLD_PACKLIST) \
		"$(PERL_ARCHLIB)\auto\$(FULLEXT)"

pure_vendor_install :: all
	$(NOECHO) $(MOD_INSTALL) \
		read "$(VENDORARCHEXP)\auto\$(FULLEXT)\.packlist" \
		write "$(DESTINSTALLVENDORARCH)\auto\$(FULLEXT)\.packlist" \
		"$(INST_LIB)" "$(DESTINSTALLVENDORLIB)" \
		"$(INST_ARCHLIB)" "$(DESTINSTALLVENDORARCH)" \
		"$(INST_BIN)" "$(DESTINSTALLVENDORBIN)" \
		"$(INST_SCRIPT)" "$(DESTINSTALLVENDORSCRIPT)" \
		"$(INST_MAN1DIR)" "$(DESTINSTALLVENDORMAN1DIR)" \
		"$(INST_MAN3DIR)" "$(DESTINSTALLVENDORMAN3DIR)"


doc_perl_install :: all
	$(NOECHO) $(ECHO) Appending installation info to "$(DESTINSTALLARCHLIB)/perllocal.pod"
	-$(NOECHO) $(MKPATH) "$(DESTINSTALLARCHLIB)"
	-$(NOECHO) $(DOC_INSTALL) \
		"Module" "$(NAME)" \
		"installed into" "$(INSTALLPRIVLIB)" \
		LINKTYPE "$(LINKTYPE)" \
		VERSION "$(VERSION)" \
		EXE_FILES "$(EXE_FILES)" \
		>> "$(DESTINSTALLARCHLIB)\perllocal.pod"

doc_site_install :: all
	$(NOECHO) $(ECHO) Appending installation info to "$(DESTINSTALLARCHLIB)/perllocal.pod"
	-$(NOECHO) $(MKPATH) "$(DESTINSTALLARCHLIB)"
	-$(NOECHO) $(DOC_INSTALL) \
		"Module" "$(NAME)" \
		"installed into" "$(INSTALLSITELIB)" \
		LINKTYPE "$(LINKTYPE)" \
		VERSION "$(VERSION)" \
		EXE_FILES "$(EXE_FILES)" \
		>> "$(DESTINSTALLARCHLIB)\perllocal.pod"

doc_vendor_install :: all
	$(NOECHO) $(ECHO) Appending installation info to "$(DESTINSTALLARCHLIB)/perllocal.pod"
	-$(NOECHO) $(MKPATH) "$(DESTINSTALLARCHLIB)"
	-$(NOECHO) $(DOC_INSTALL) \
		"Module" "$(NAME)" \
		"installed into" "$(INSTALLVENDORLIB)" \
		LINKTYPE "$(LINKTYPE)" \
		VERSION "$(VERSION)" \
		EXE_FILES "$(EXE_FILES)" \
		>> "$(DESTINSTALLARCHLIB)\perllocal.pod"

```

**Comment by shawnlaffan** [comment]
Editing the install target in the Makefile to this seems to work (or at least not mess up a non-parallel install of Alien::sqlite on windows):

```make
install: 
	$(MAKE) alien_clean_install
	$(MAKE) pure_install 
	$(MAKE) doc_install
	$(NOECHO) $(NOOP)
```


If ExtUtils::MakeMaker is consistent then Alien::Build::MM::mm_install could change the install line in its $section using a regex. 
https://metacpan.org/source/PLICEASE/Alien-Build-2.23/lib/Alien/Build/MM.pm#L243

**Comment by plicease** [comment]
I really don't want to have to modify the generated install section (just prepend), seems like opening up a can of worms.  I had trouble with parallel make early on in the postamble section as well, and at one point I thought we were using `.NOTPARALLEL` (gmake) or `.NO_PARALLEL` (pmake), but I don't see its use anymore, so I may have been able to refactor that section to work under parallel.  (It's probably worth doing some code archeology to verify).  I think if we can't get refactor the install step to work in parallel then we should just disable parallel make in the EUMM generated `Makefile`.  There isn't much benefit from parallelizing the EUMM `Makefile`, and you can still build the alienized package in parallel if it supports it using `MAKEFLAGS` as you describe.

**Comment by shawnlaffan** [comment]
Yes, modifying a generated file is somewhat fraught.  Disabling parallelisation entirely in the EUMM makefile looks like a decent solution to me given the Alien will still see $MAKEFLAGS.

**Comment by plicease** [comment]
I'd accept a patch that adds `.NOTPARALLEL` AND `.NO_PARALLEL` to the install section (I _believe_ the postamble section is parallel safe, but if you can show it not to be we can add it there instead), if you can test and verify that works for you.

**Comment by shawnlaffan** [comment]
Will prep a PR.

**Comment by plicease** [comment]
I did a dev release with your fix just now.  I will try to some testing with actual downstream dists and do a release in a week or so if things look good.

**Comment by shawnlaffan** [comment]
Thanks.  This one does need downstream testing before it goes mainstream.

**Comment by shawnlaffan** [comment]
FWIW, the fix seems to work with CI on my Alien canary repo.  Each dependent alien repo uses clean_install for these runs.

Alien::Build@2.20 fails and is missing files:
https://github.com/shawnlaffan/geo-gdal-ffi-canary/commit/b7c5cb5143902512b151c8fda485b92c7f4e3394

Alien::Build@2.24_1 passes and has all the files (the Travis MacOS fail is a timeout):
https://github.com/shawnlaffan/geo-gdal-ffi-canary/commit/6f5a08d617e92e7a295ced5f577ce0f5bb3b2458
