### ISSUE TITLE
MetaCPAN indexing issue for Alien-Build-2.25

### ISSUE THREAD

**Issue by dbevans** [Perl5-Alien/Alien-Build#204]
While the module is visible at https://metacpan.org/pod/Alien::Build, 
querying the MetaCPAN API at https://fastapi.metacpan.org/v1/release/Alien-Build/ returns 
```
{
   "code" : 404,
   "message" : "Not found"
}
```

Used by MacPorts to check for updates.

**Comment by plicease** [comment]
This is a bug in metacpan:
https://github.com/metacpan/metacpan-web/issues/2307
https://github.com/metacpan/metacpan-web/issues/2306

**Comment by dbevans** [comment]
Thanks for the explaination.  This seems to happen sporadically and not just with this module.  I've worked around this in MacPorts for now.

**Comment by plicease** [comment]
Looks like 2.26 is correctly index in metacpan.
