### ISSUE TITLE
Plugin to override ALIEN_INSTALL_TYPE on specific aliens.

### ISSUE THREAD

**Issue by plicease** [Perl5-Alien/Alien-Build#25]
Useful in CI, as you may be testing a specific install type for the main component that you are testing, but want specific Aliens to use system.  Or perhaps you want it to revert to the default logic.

This will probably require some hooks into the Alien-Build core, I don't think it is possible to purely from a plugin atm.

Plugin should be distributed separately from the AB core.

**Comment by wbraswell** [comment]
Inspired by some AppVeyor "hack" code:

https://github.com/wbraswell/alien-pcre2/blob/b2e9b6533a9c8b7e0e9314d8eacf921bc892fe71/appveyor.yml#L44-L58

Discussion details here:

https://irclog.perlgeek.de/native/2017-07-23

**Comment by plicease** [comment]
I've added two plugins that I think handle most of the use cases that are needed here.  They use heuristics for determining the dist name of the alien, since an `alienfile` doesn't have this information.

`Probe::Override`
https://metacpan.org/pod/release/PLICEASE/Alien-Build-Plugin-Probe-Override-0.01/lib/Alien/Build/Plugin/Probe/Override.pm

Lets you override the install type on an per-alien basis in your `~/.alienbuild/rc.pl` file.  This is useful for production build environments that might want to enforce say `Alien::gmake` is installed as `system` and `Alien::FFI` is installed as `share`.

`Probe::OverrideCI`
https://metacpan.org/pod/release/PLICEASE/Alien-Build-Plugin-Probe-Override-0.01/lib/Alien/Build/Plugin/Probe/OverrideCI.pm

Lets you override the install type for just the main project that is being tested in CI, and fallback on the default detection logic for dependencies.  (compatible with travis-ci and appveyor, additional CI support are possible; patches welcome).  It uses the CI's build root environment variable to differentiate between the main project and modules that are installed via `cpanm`, etc.
