### ISSUE TITLE
CBuilder In Windows, Misleading System Probe Error Message

### ISSUE THREAD

**Issue by wbraswell** [Perl5-Alien/Alien-Build#27]
This issue only seems to occur in Windows:

https://ci.appveyor.com/project/wbraswell/alien-jpcre2/build/1.0.94#L3260

    perl Makefile.PL
    Alien::Build::Plugin::Probe::CBuilder> trying: cflags=-IC:/strawberry/perl/site/lib/auto/share/dist/Alien-PCRE2/include -DPCRE2_STATIC  libs=-LC:/strawberry/perl/site/lib/auto/share/dist/Alien-PCRE2/lib -lpcre2-8 
    Alien::Build::Plugin::Probe::CBuilder> compile failed: error building xs.dll file from 'mytest.c' at C:/strawberry/perl/lib/ExtUtils/CBuilder/Platform/Windows.pm line 129.
    Alien::Build::Plugin::Probe::CBuilder> compile failed: gcc -c -s -O2 -DWIN32 -D__USE_MINGW_ANSI_STDIO -DPERL_TEXTMODE_SCRIPTS -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -DUSE_PERLIO -fwrapv -fno-strict-aliasing -mms-bitfields -IC:/strawberry/perl/site/lib/auto/share/dist/Alien-PCRE2/include -DPCRE2_STATIC -s -O2 -I"C:\STRAWB~1\perl\lib\CORE" -I"C:\STRAWB~1\c\include" -o "mytest.o" "mytest.c"
    mytest.c:1:10: fatal error: jpcre2.hpp: No such file or directory
     #include <jpcre2.hpp>
              ^~~~~~~~~~~~
    compilation terminated.
    Alien::Build> error in probe (will do a share install): error building xs.dll file from 'mytest.c' at C:/strawberry/perl/lib/ExtUtils/CBuilder/Platform/Windows.pm line 129.

The same build in Linux does not show any of this output whatsoever:

https://travis-ci.org/wbraswell/alien-jpcre2/jobs/257523753#L6173

This has already been mis-reported to me as an error building Alien::JPCRE2 in Windows, so we definitely need to somehow hide the error or otherwise let the users know not to panic when they see this compile error message.

**Comment by plicease** [comment]
This is not an error.  The diagnostic output is necessary to see why the probe failed.

**Comment by plicease** [comment]
I will add this to the diagnostic:  d65edc5dc73183d336e8cdb82a10fa2645a06905 hopefully avoid people unnecessarily opening tickets.

**Comment by wbraswell** [comment]
@plicease 
Thanks for adding the "don't panic!" output, that should help.
My only remaining question...  why does is this error code output generated only in Windows and not in Linux?

**Comment by plicease** [comment]
Not sure I see it in OS X.

**Comment by wbraswell** [comment]
I don't currently have access to a Mac testing box, just Linux in Travis & Windows in AppVeyor, so I only know about those two platforms.

**Comment by plicease** [comment]
I also see it in Linux:

```
ratbat% perl Makefile.PL 
Alien::Build::Plugin::Fetch::Rewrite> init
Alien::Build::Plugin::Probe::CBuilder> trying: cflags=-I/home/ollisg/perl5/lib/perl5/x86_64-linux-gnu-thread-multi/auto/share/dist/Alien-PCRE2/include -DPCRE2_STATIC   libs=-L/home/ollisg/perl5/lib/perl5/x86_64-linux-gnu-thread-multi/auto/share/dist/Alien-PCRE2/lib -lpcre2-8  
Alien::Build::Plugin::Probe::CBuilder> compile failed: error building mytest.o from 'mytest.c' at /usr/share/perl/5.24/ExtUtils/CBuilder/Base.pm line 174.
Alien::Build::Plugin::Probe::CBuilder> compile failed: x86_64-linux-gnu-gcc -I/usr/lib/x86_64-linux-gnu/perl/5.24/CORE -fPIC -I/home/ollisg/perl5/lib/perl5/x86_64-linux-gnu-thread-multi/auto/share/dist/Alien-PCRE2/include -DPCRE2_STATIC -c -x c++ -D_REENTRANT -D_GNU_SOURCE -DDEBIAN -fwrapv -fno-strict-aliasing -pipe -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O2 -g -o mytest.o mytest.c
mytest.c:1:22: fatal error: jpcre2.hpp: No such file or directory
 #include <jpcre2.hpp>
                      ^
compilation terminated.
Alien::Build> error in probe (will do a share install): error building mytest.o from 'mytest.c' at /usr/share/perl/5.24/ExtUtils/CBuilder/Base.pm line 174.
Generating a Unix-style Makefile
Writing Makefile for Alien::JPCRE2
Writing MYMETA.yml and MYMETA.json
```

**Comment by plicease** [comment]
Ah.  Probably you have ALIEN_INSTALL_TYPE set in the Linux CI:

```
ratbat% env ALIEN_INSTALL_TYPE=share perl Makefile.PL 
Alien::Build::Plugin::Fetch::Rewrite> init
Generating a Unix-style Makefile
Writing Makefile for Alien::JPCRE2
Writing MYMETA.yml and MYMETA.json
```

**Comment by wbraswell** [comment]
OH YES that's it!  Thanks for helping figure that out.  :-)

https://github.com/wbraswell/alien-jpcre2/blob/d57e2dc29eaf23fa7909bbf2f510a23d805fc4bf/.travis.yml#L83
