### ISSUE TITLE
ExtUtils::ParseXS needs a version bump

### ISSUE THREAD

**Issue by zmughal** [Perl5-Alien/Alien-Build#28]
As I was working on [p5-Alien-OpenJPEG](https://github.com/project-renard/p5-Alien-OpenJPEG/tree/6d7c21c30cbe5d4b6357d95eac1220802c5ff91e), I noticed that my builds were failing on [Travis just on perl-5.20](https://travis-ci.org/project-renard/p5-Alien-OpenJPEG/builds/260416411).

After replicating and comparing module versions, I was able to get the following results that suggest we need an ExtUtils::ParseXS@3.30 minimum:

```shell
vagrant@vagrant-ubuntu-trusty-64:~/project-renard/p5-Alien-OpenJPEG/p5-Alien-OpenJPEG/build-dir-5.20$ for version in 3.21 3.24 3.30 3.35; do cpanm ExtUtils::ParseXS@$version -nq >/dev/null 2>&1; echo -en "ExtUtils::ParseXS@$version\t"; perl -Iblib/lib t/version.t >/dev/null 2>&1 && echo 'success' || echo 'fail'; done

ExtUtils::ParseXS@3.21  fail
ExtUtils::ParseXS@3.24  fail
ExtUtils::ParseXS@3.30  success
ExtUtils::ParseXS@3.35  success
```

**Comment by plicease** [comment]
This is in 0.82
