### ISSUE TITLE
Improve CI coverage on Windows (Appveyor love)

### ISSUE THREAD

**Issue by plicease** [Perl5-Alien/Alien-Build#36]
## Abstract

It would be good to get better coverage on appveyor.  At the moment we are using the last major version of Strawberry 5.24.0 (dmake) and not the latest Strawberry 5.26.0 (gmake).  Since that is a major configuration change that AB has to deal with it would be good to test both.  It would also be good to test Cygwin and MSYS / MinGW.  Testing 64 bit Perls may also be useful, but probably less so.

## Matrix Items

(Even some useful subset of these would be useful)

 - <strike>Strawberry Perl x86 5.24.0</strike>
 - <strike>Strawberry Perl x64 5.24.0</strike>
 - Strawberry Perl x86 5.26.0
 - Strawberry Perl x64 5.26.0
 - cygwin (whatever is installed on appveyor)
 - MSYS2 / MinGW x86
 - MSYS2 / MinGW x64
 - ActiveState Perl (whatever is installed on appveyor)

## Additional testing

After testing, AB should be installed, and then we should build some key Aliens to make sure they work.  Not 100% sure which are best but candidates:

 - Alien::Autotools
 - Alien::gmake
 - Alien::libuv
 - ...

**Comment by lancew** [comment]
According to https://www.appveyor.com/docs/build-environment/#perl
Perl 5.20.1.2000 x86 (C:\Perl in PATH)

So the Appveyor default is 5.20 I believe.

Perhaps berrybrew? https://github.com/dnmfarrell/berrybrew

**Comment by plicease** [comment]
With CI now using gh actions we are testing the latest version of strawberry, and appveyor is testing key older versions of strawberry.  I've personally dropped development on cygwin so that is not likely to be added to ci anytime soon.  ActiveState Perl is a dumpster fire.  MSYS2 might be interesting, and patches welcome there.  For now I am going to close this as doneish since it seems unlikely that we will get any further given current resources.
