### ISSUE TITLE
version 1.32 is not indexed correctly

### ISSUE THREAD

**Issue by chorny** [Perl5-Alien/Alien-Build#49]
02packages.details.txt:
```
Alien::Build                       1.28  P/PL/PLICEASE/Alien-Build-1.28.tar.gz
...
Alien::Build::Plugin::Gather::IsolateDynamic 1.32  P/PL/PLICEASE/Alien-Build-1.32.tar.gz
```

**Comment by plicease** [comment]
Thanks for raising this.  Looks like this was a PAUSE indexing error and I missed the notification.  I've forced reindexed this dist, and the response came back good, so I believe this is resolved.
