### ISSUE TITLE
add data_dir method

### ISSUE THREAD

**Issue by shawnlaffan** [Perl5-Alien/Alien-Build#57]
A few distributions include a data directory in addition to the bin and lib dirs.  It would be useful if there were a method in Alien::Base to access it, per shawnlaffan/perl-alien-gdal#12 .  

I have a method in Alien::gdal that seems to work well enough for my use case, but it could probably be more generic.

**Comment by plicease** [comment]
I like what you have done, and will have to give it some thought.

**Comment by plicease** [comment]
After some though, I don't think we can do this for the general case.  For a share install it shouldn't be a problem, but for a system install there isn't a reliable way to find a the tools data directory.  For individual packages there may or may not be a good way to do it, and for that you can write a subroutine in the subclass.
