### ISSUE TITLE
Undeclared dependencies

### ISSUE THREAD

**Issue by shawnlaffan** [Perl5-Alien/Alien-Build#63]
It appears there are some dependencies that aren't detected by the build process.  

```
URI
URI::file
URI::Escape
File::Listing
```

The upshot is CPAN test failures in my Alien plugin module Alien::Build::Plugin::Cleanse::BuildDir, e.g.:
http://www.cpantesters.org/cpan/report/d15f1884-9445-11e8-98d5-bb14e5798fec

These are called conditionally, e.g. ```$meta->add_requires('share' => 'URI' => 0 );``` so have been missed by the dependency scanning in the build process (if my understanding of Dist::Zilla is correct).

https://github.com/Perl5-Alien/Alien-Build/blob/e758bdac985c660c1206d89ff23229256b6aa6bd/lib/Alien/Build/Plugin/Fetch/Local.pm#L66

https://github.com/Perl5-Alien/Alien-Build/blob/7978379f52d7fbed31255feaeb9ea4123f16d646/lib/Alien/Build/Plugin/Decode/DirListing.pm#L32

I note that the Alien::Base tests that use URI are conditional, so maybe you already know about this.  https://github.com/Perl5-Alien/Alien-Build/blob/177af53c52b12b79342dc5ebb452bc4c5b490538/t/alien_build_plugin_fetch_local.t#L140

It's simple enough for me to work around, but should perhaps be fixed upstream.

Thanks,
Shawn.

**Comment by shawnlaffan** [comment]
Thanks for clarifying.  

Skipping isn't an option in this case.  It needs to be able to download (copy and extract) and build the test alien so it can be cleaned up afterwards, as that's the purpose of the plugin.  

I'll add the relevant deps to the plugin's Makefile.PL.

**Comment by plicease** [comment]
Yeah, but your plugin only does something on a `share` install.  Those prereqs should be dynamic IMO.

Another option is to write simplified download/extract stage in the test that won't pull in any prereqs, like here:

**Comment by shawnlaffan** [comment]
Thanks again.  I'll give that approach a go.

**Comment by plicease** [comment]
Cool.  I appreciate this discussion.  I have opened some other tickets to address the design issues, but since I think they may not be relevant, I am going to close this issue.

**Comment by shawnlaffan** [comment]
No worries.  Your suggested approach works.  I'll upload a new plugin version to cpan sometime today.
