### ISSUE TITLE
Test::Alien run_ok fails to find bin in /usr/local/bin on FreeBSD

### ISSUE THREAD

**Issue by robrwo** [Perl5-Alien/Alien-Build#68]
It seems that run_ok is not finding a an executable when a package is already installed on FreeBSD, in /usr/local/bin.

See https://github.com/robrwo/Alien-TidyHTML5/issues/2

**Comment by eserte** [comment]
@robrwo I am not sure. I see that `File::Which::which` and `system` are used in `run_ok`, and both should obey `$ENV{PATH}` (which by default includes `/usr/local/bin` on BSD systems).

**Comment by plicease** [comment]
I think `run_ok` was doing the right thing in this case.  Please see

https://github.com/robrwo/Alien-TidyHTML5/issues/2
https://github.com/robrwo/Alien-TidyHTML5/pull/3
