### ISSUE TITLE
`probe` commands can't be split lists of arguments

### ISSUE THREAD

**Issue by leonerd** [Perl5-Alien/Alien-Build#76]
Shell commands used in some blocks of code allow splitting of strings, e.g.

```perl
build [
  [ '%{make}', 'PREFIX=%{.install.prefix}', 'install' ],
]
```

It seems that `probe` does not. If I do

```perl
probe [ "pkg-config $modname --atleast-version 2.0.0" ];
```

then it works fine, but if I do

```perl
probe [ 'pkg-config', $modname, '--atleast-version', '2.0.0' ];
```

I get the failure:

```
$ perl Build.PL 
Alien::Build::CommandSequence> + pkg-config
Must specify package names on the command line
Alien::Build> error in probe (will do a share install): external command failed at /home/leo/lib/perl5/Alien/Build/CommandSequence.pm line 87.
```

This *may* just be a matter of documenting "well don't do that", but if there's no particular reason why it should be allowed in some places and not others, it might be easiest just to allow it everywhere.

**Comment by plicease** [comment]
I think what you mean is:

```perl
probe [ [ 'pkg-config', $modname, '--atleast-version', '2.0.0']  ];
```

**Comment by plicease** [comment]
You can also use 

```perl
plugin 'PkgConfig' => (
  pkg_name => 'libfoo',
  minimum_version => '2.0.0',
);
```

**Comment by plicease** [comment]
closing, please let me know if my first comment doesn't solve this issue for you.

**Comment by leonerd** [comment]
Ahyes, that looks fine. The subtle distinction of `[]` vs `[ []... ]` was what was throwing me.
